import { Profile } from "../interfaces/profile-interface";

export const usersData: Profile[] = [
  {
    userAddress: "123 Maple Street",
    userId: 101,
    userCity: "Springfield",
    userCountry: "USA",
    userEmail: "john.doe@example.com",
    userFirstName: "John",
    userGender: "Male",
    userImage: "https://example.com/images/john_doe.jpg",
    userLastName: "Doe",
    userPhone: 5551234567,
    userRoleName: "Admin",
    userState: "Illinois",
    userPassword: "Test@123",
  },
  {
    userAddress: "456 Oak Avenue",
    userId: 102,
    userCity: "Metropolis",
    userCountry: "USA",
    userEmail: "jane.smith@example.com",
    userFirstName: "Jane",
    userGender: "Female",
    userImage: "https://example.com/images/jane_smith.jpg",
    userLastName: "Smith",
    userPhone: 5552345678,
    userRoleName: "Developer",
    userState: "New York",
    userPassword: "Test@123",
  },
  {
    userAddress: "789 Pine Lane",
    userId: 103,
    userCity: "Gotham",
    userCountry: "USA",
    userEmail: "alice.johnson@example.com",
    userFirstName: "Alice",
    userGender: "Female",
    userImage: "https://example.com/images/alice_johnson.jpg",
    userLastName: "Johnson",
    userPhone: 5553456789,
    userRoleName: "Manager",
    userState: "California",
    userPassword: "Test@123",
  },
  {
    userAddress: "321 Birch Road",
    userId: 104,
    userCity: "Star City",
    userCountry: "USA",
    userEmail: "bob.brown@example.com",
    userFirstName: "Bob",
    userGender: "Male",
    userImage: "https://example.com/images/bob_brown.jpg",
    userLastName: "Brown",
    userPhone: 5554567890,
    userRoleName: "Admin",
    userState: "Florida",
    userPassword: "Test@123",
  },
  {
    userAddress: "654 Cedar Court",
    userId: 105,
    userCity: "Central City",
    userCountry: "USA",
    userEmail: "charlie.davis@example.com",
    userFirstName: "Charlie",
    userGender: "Male",
    userImage: "https://example.com/images/charlie_davis.jpg",
    userLastName: "Davis",
    userPhone: 5555678901,
    userRoleName: "Developer",
    userState: "Texas",
    userPassword: "Test@123",
  },
  {
    userAddress: "987 Elm Street",
    userId: 106,
    userCity: "Smallville",
    userCountry: "USA",
    userEmail: "diana.evans@example.com",
    userFirstName: "Diana",
    userGender: "Female",
    userImage: "https://example.com/images/diana_evans.jpg",
    userLastName: "Evans",
    userPhone: 5556789012,
    userRoleName: "Manager",
    userState: "Ohio",
    userPassword: "Test@123",
  },
  {
    userAddress: "159 Spruce Drive",
    userId: 107,
    userCity: "Coast City",
    userCountry: "USA",
    userEmail: "edward.franklin@example.com",
    userFirstName: "Edward",
    userGender: "Male",
    userImage: "https://example.com/images/edward_franklin.jpg",
    userLastName: "Franklin",
    userPhone: 5557890123,
    userRoleName: "Admin",
    userState: "Nevada",
    userPassword: "Test@123",
  },
  {
    userAddress: "753 Maplewood Lane",
    userId: 108,
    userCity: "Keystone City",
    userCountry: "USA",
    userEmail: "frank.harris@example.com",
    userFirstName: "Frank",
    userGender: "Male",
    userImage: "https://example.com/images/frank_harris.jpg",
    userLastName: "Harris",
    userPhone: 5558901234,
    userRoleName: "Developer",
    userState: "Colorado",
    userPassword: "Test@123",
  },
  {
    userAddress: "852 Chestnut Blvd",
    userId: 109,
    userCity: "Blüdhaven",
    userCountry: "USA",
    userEmail: "grace.ingram@example.com",
    userFirstName: "Grace",
    userGender: "Female",
    userImage: "https://example.com/images/grace_ingram.jpg",
    userLastName: "Ingram",
    userPhone: 5559012345,
    userRoleName: "Manager",
    userState: "Arizona",
    userPassword: "Test@123",
  },
  {
    userAddress: "741 Oakridge Ave",
    userId: 110,
    userCity: "Ivy Town",
    userCountry: "USA",
    userEmail: "hannah.james@example.com",
    userFirstName: "Hannah",
    userGender: "Female",
    userImage: "https://example.com/images/hannah_james.jpg",
    userLastName: "James",
    userPhone: 5550123456,
    userRoleName: "Admin",
    userState: "Georgia",
    userPassword: "Test@123",
  },
  {
    userAddress: "963 Willow Way",
    userId: 111,
    userCity: "Opal City",
    userCountry: "USA",
    userEmail: "ian.kent@example.com",
    userFirstName: "Ian",
    userGender: "Male",
    userImage: "https://example.com/images/ian_kent.jpg",
    userLastName: "Kent",
    userPhone: 5551234568,
    userRoleName: "Developer",
    userState: "Virginia",
    userPassword: "Test@123",
  },
  {
    userAddress: "357 Evergreen Terrace",
    userId: 112,
    userCity: "Hub City",
    userCountry: "USA",
    userEmail: "julia.lucas@example.com",
    userFirstName: "Julia",
    userGender: "Female",
    userImage: "https://example.com/images/julia_lucas.jpg",
    userLastName: "Lucas",
    userPhone: 5552345679,
    userRoleName: "Manager",
    userState: "Washington",
    userPassword: "Test@123",
  },
  {
    userAddress: "258 Redwood Place",
    userId: 113,
    userCity: "Fawcett City",
    userCountry: "USA",
    userEmail: "kevin.morgan@example.com",
    userFirstName: "Kevin",
    userGender: "Male",
    userImage: "https://example.com/images/kevin_morgan.jpg",
    userLastName: "Morgan",
    userPhone: 5553456790,
    userRoleName: "Admin",
    userState: "Oregon",
    userPassword: "Test@123",
  },
  {
    userAddress: "159 Aspen Drive",
    userId: 114,
    userCity: "Gateway City",
    userCountry: "USA",
    userEmail: "laura.nelson@example.com",
    userFirstName: "Laura",
    userGender: "Female",
    userImage: "https://example.com/images/laura_nelson.jpg",
    userLastName: "Nelson",
    userPhone: 5554567891,
    userRoleName: "Developer",
    userState: "Maine",
    userPassword: "Test@123",
  },
  {
    userAddress: "753 Pinecrest Way",
    userId: 115,
    userCity: "Ivy City",
    userCountry: "USA",
    userEmail: "michael.owen@example.com",
    userFirstName: "Michael",
    userGender: "Male",
    userImage: "https://example.com/images/michael_owen.jpg",
    userLastName: "Owen",
    userPhone: 5555678902,
    userRoleName: "Manager",
    userState: "Vermont",
    userPassword: "Test@123",
  },
  {
    userAddress: "963 Oakwood Blvd",
    userId: 116,
    userCity: "Gotham Heights",
    userCountry: "USA",
    userEmail: "nina.parker@example.com",
    userFirstName: "Nina",
    userGender: "Female",
    userImage: "https://example.com/images/nina_parker.jpg",
    userLastName: "Parker",
    userPhone: 5556789013,
    userRoleName: "Developer",
    userState: "Mississippi",
    userPassword: "Test@123",
  },
  {
    userAddress: "147 Beechwood Blvd",
    userId: 117,
    userCity: "New Carthage",
    userCountry: "USA",
    userEmail: "oliver.quinn@example.com",
    userFirstName: "Oliver",
    userGender: "Male",
    userImage: "https://example.com/images/oliver_quinn.jpg",
    userLastName: "Quinn",
    userPhone: 5557891234,
    userRoleName: "Developer",
    userState: "South Carolina",
    userPassword: "Test@123",
  },
  {
    userAddress: "963 Magnolia Drive",
    userId: 118,
    userCity: "Midway City",
    userCountry: "USA",
    userEmail: "paula.reed@example.com",
    userFirstName: "Paula",
    userGender: "Female",
    userImage: "https://example.com/images/paula_reed.jpg",
    userLastName: "Reed",
    userPhone: 5558902345,
    userRoleName: "Manager",
    userState: "Indiana",
    userPassword: "Test@123",
  },
  {
    userAddress: "789 Birch Way",
    userId: 119,
    userCity: "Dakota City",
    userCountry: "USA",
    userEmail: "quentin.sanders@example.com",
    userFirstName: "Quentin",
    userGender: "Male",
    userImage: "https://example.com/images/quentin_sanders.jpg",
    userLastName: "Sanders",
    userPhone: 5559013456,
    userRoleName: "Admin",
    userState: "Kentucky",
    userPassword: "Test@123",
  },
];
